# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-16 22:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0002_auto_20180716_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='course_desc',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='DESC', serialize=False, to='Course.Course'),
        ),
    ]
